In [1]:
import torch


In [2]:

a = torch.randn(4)
a


tensor([ 0.0460,  1.0073, -0.0578, -0.9420])

In [3]:
a.add(10)

tensor([10.0460, 11.0073,  9.9422,  9.0580])

In [4]:
a + 10

tensor([10.0460, 11.0073,  9.9422,  9.0580])

In [5]:

torch.add(a, 20)


tensor([20.0460, 21.0073, 19.9422, 19.0580])

In [6]:

b = torch.randn(4)
b


tensor([ 1.9038,  0.3293, -0.5187, -0.0831])

In [7]:

c = torch.randn(4, 1)
c


tensor([[ 0.2040],
        [-0.0988],
        [-0.3849],
        [-1.1460]])

In [8]:

torch.add(b, c, alpha=10)



tensor([[  3.9438,   2.3693,   1.5214,   1.9570],
        [  0.9161,  -0.6584,  -1.5063,  -1.0707],
        [ -1.9449,  -3.5194,  -4.3673,  -3.9317],
        [ -9.5561, -11.1306, -11.9786, -11.5430]])

In [9]:

x = torch.randn(2, 3,3,3)
x


tensor([[[[ 8.0421e-02,  1.3259e+00, -2.7006e-01],
          [ 1.9684e-01, -2.1261e+00,  1.4051e-01],
          [ 5.2404e-01, -8.5610e-01, -2.3880e-01]],

         [[ 1.2307e-01,  1.2916e+00, -7.9914e-02],
          [ 6.4524e-01, -3.6283e-01, -1.0227e-01],
          [-3.1229e-02,  1.1138e+00,  9.0743e-01]],

         [[-1.8901e+00,  7.3384e-01,  5.3559e-02],
          [ 1.3577e+00,  1.3136e+00, -6.3667e-04],
          [ 1.5157e+00,  2.8827e+00, -2.6406e-01]]],


        [[[-1.5198e+00, -9.4519e-01,  7.9987e-01],
          [-4.3078e-01,  2.4529e+00, -5.3376e-01],
          [-4.7262e-01,  2.5982e-01,  3.1526e-01]],

         [[ 7.5396e-01,  9.1633e-02, -2.2287e-01],
          [ 5.7521e-01, -9.2551e-01,  7.8175e-01],
          [ 8.2501e-02, -7.3902e-01, -2.6647e+00]],

         [[ 1.0913e+00,  1.6182e+00, -1.5155e+00],
          [-4.3511e-01,  1.1537e+00,  8.8978e-01],
          [-5.6238e-01, -1.2073e+00,  2.6020e-01]]]])

In [10]:

torch.cat((x, x, x), 0)


tensor([[[[ 8.0421e-02,  1.3259e+00, -2.7006e-01],
          [ 1.9684e-01, -2.1261e+00,  1.4051e-01],
          [ 5.2404e-01, -8.5610e-01, -2.3880e-01]],

         [[ 1.2307e-01,  1.2916e+00, -7.9914e-02],
          [ 6.4524e-01, -3.6283e-01, -1.0227e-01],
          [-3.1229e-02,  1.1138e+00,  9.0743e-01]],

         [[-1.8901e+00,  7.3384e-01,  5.3559e-02],
          [ 1.3577e+00,  1.3136e+00, -6.3667e-04],
          [ 1.5157e+00,  2.8827e+00, -2.6406e-01]]],


        [[[-1.5198e+00, -9.4519e-01,  7.9987e-01],
          [-4.3078e-01,  2.4529e+00, -5.3376e-01],
          [-4.7262e-01,  2.5982e-01,  3.1526e-01]],

         [[ 7.5396e-01,  9.1633e-02, -2.2287e-01],
          [ 5.7521e-01, -9.2551e-01,  7.8175e-01],
          [ 8.2501e-02, -7.3902e-01, -2.6647e+00]],

         [[ 1.0913e+00,  1.6182e+00, -1.5155e+00],
          [-4.3511e-01,  1.1537e+00,  8.8978e-01],
          [-5.6238e-01, -1.2073e+00,  2.6020e-01]]],


        [[[ 8.0421e-02,  1.3259e+00, -2.7006e-01],
          [ 1.9

In [11]:
x.size()

torch.Size([2, 3, 3, 3])

In [16]:

c=torch.cat((x,x), 4)
c.size()

IndexError: Dimension out of range (expected to be in range of [-4, 3], but got 4)

In [ ]:
c.size()

torch.Size([2, 9, 3, 3])